# Generated by Django 5.1.1 on 2024-10-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appli_ParcourSup', '0002_etablissement_formation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='etablissement',
            field=models.CharField(max_length=50),
        ),
    ]
