# Generated by Django 5.1.1 on 2024-10-23 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appli_ParcourSup', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
