# Generated by Django 5.1.1 on 2024-10-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appli_ParcourSup', '0006_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_type',
            new_name='status',
        ),
    ]
