# Generated by Django 5.1.1 on 2024-11-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appli_ParcourSup', '0007_rename_user_type_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='formations_images/'),
        ),
    ]
