# Generated by Django 5.1.1 on 2024-11-05 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appli_ParcourSup', '0009_alter_formation_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='candidats',
            field=models.ManyToManyField(blank=True, related_name='postulations', to=settings.AUTH_USER_MODEL),
        ),
    ]
