# Generated by Django 5.1.1 on 2024-11-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appli_ParcourSup', '0012_remove_formation_candidats'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=10),
        ),
    ]
